In [56]:
import numpy as np 

#Using the function arange, create an array of 10 integers 'd' from -20 to 25 (inclusive), in steps of 5.

d = np.arange(start=-20, stop= 30, step=5)
print("d:", d)


d: [-20 -15 -10  -5   0   5  10  15  20  25]


In [39]:
#Multiply all values in d by 10, storing the result in d2.
d2 = d * 10








In [61]:
#Add the values stored in d and d2, element-wise, printing the result to the console
print(d2 + d3)

NameError: name 'i' is not defined

In [45]:
#Reshape d2 into a 5x2 array, storing the result in d2.
d2 = np.reshape(d2,(5,2))



[[-200 -150]
 [-100  -50]
 [   0   50]
 [ 100  150]
 [ 200  250]]


In [62]:
#Create an array d3, containing the integers 1,2,3,4,5.
d3 = np.array([1,2,3,4,5])
print(d3)

[1 2 3 4 5]


In [63]:
#Reshape d3 into the necessary shape such that d2*d3 succeeds (hint: broadcasting). Save the result of d2*d3 into d4, and print d4 toto the console.
d3 = np.reshape(d3, (5,1))

d4 = (d2 * d3)
print(d4)

[[-200 -150]
 [-200 -100]
 [   0  150]
 [ 400  600]
 [1000 1250]]


In [64]:
#Print to the console the 1st, 3rd and 5th rows, both columns, of d4. 
print(d4[0:6:2,:])


[[-200 -150]
 [   0  150]
 [1000 1250]]


In [65]:
#Print the object ID of d4 to the console.
d5 = id(d4)
print(d5)

1743194904400


In [66]:
#Resize (not reshape) d4 into a 2x5 array.
d4.resize(2,5)

In [69]:
#Flatten (not reshape) d4 back into a 10x1 array. Print the result to the console. Your output should match: [-200 -150 -200 -100 0 150 400 600 1000 1250]
d4 = d4.flatten()
print("Fattened:", d4)

Fattened: [-200 -150 -200 -100    0  150  400  600 1000 1250]
